#
# [389] Find the Difference
#
# https://leetcode.com/problems/find-the-difference
#
# Easy (51.56%)
# Total Accepted:    
# Total Submissions: 
# Testcase Example:  '"abcd"\n"abcde"'
#
# 
# Given two strings s and t which consist of only lowercase letters.
# 
# String t is generated by random shuffling string s and then add one more
# letter at a random position.
# 
# Find the letter that was added in t.
# 
# Example:
# 
# Input:
# s = "abcd"
# t = "abcde"
# 
# Output:
# e
# 
# Explanation:
# 'e' is the letter that was added.
# 
#
class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        char_map = dict()
        for index1, char1 in enumerate(t):
            if char1 not in char_map:
                char_map[char1] = 0
            char_map[char1] += 1
        for index2, char2 in enumerate(s):
            char_map[char2] -= 1
        for key in char_map:
            if char_map[key] == 1:
                return key
